apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dicee-job
spec :
  backoffLimit: 1000      
  completions : 3
  parallelism : 3
  template :
     spec:
        containers:
          - image: kodekloud/throw-dice
            name: throw-dicei
        restartPolicy : Never
